# Generated by Django 4.0.4 on 2022-04-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='registrationNumber',
            field=models.TextField(default=None, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
